services:
  db:
    image: postgres:14-alpine
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - database.env
  
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   # env_file:
  #   #   - .env
  #   volumes:
  #     - ./src:/code
  #   ports:
  #     - "8020:8020"
  #   depends_on:
  #     - db

  # redis:
  #   image: redis
  
  # broker:
  #   image: rabbitmq

volumes:
  database-data:
